server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://39.106.51.31:3306/fengwei?useUnicode=true&characterEncoding=utf8
        username: root
        password: 317812
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: service-helloworld
# MyBatis
mybatis:
    typeAliasesPackage: org.spring.springboot.domain
    mapperLocations: classpath:mapper/*.xml
    #configLocation: classpath:/mybatis-config.xml
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。

